### ISSUE TITLE
Unreliable map changes

### ISSUE THREAD

**Issue by pkoehlers** [pkoehlers/maploader#3]
Sometimes the maploader seems to successfully unpack the desired map files and backup the old map, but after the reload the map of the robot is empty.

I assume this is some syncing issue / conflict with some other process running on the robot.

Needs further investigation.

**Comment by Jokuh** [comment]
What do you mean by "the map of the robot is empty"?
If you mean that Valetudo says: "no map data. that is resolved by starting a cleaning job on the robot. As [I was reading up on Valetudo](https://github.com/Hypfer/Valetudo/discussions/1291) that seems to be caused by the robot not broadcasting the map to valetudo.

**Comment by pkoehlers** [comment]
That's what I thought at first too. 

But I actually logged into the robot, and saw in the logs that the maploader unpacked map with id e.g. 9, but the map actually had another ID and was really empty. Even after starting the full clean

**Comment by pkoehlers** [comment]
Fixed with release 1.2.0
